---
- block: # Pre-generate configurations
  - name: Create HAProxy docker-compose file
    template:
      src: "{{ docker_compose_webstack_template_file }}"
      dest: "{{ docker_compose_webstack_docker_compose_file_path }}"
    register: docker_compose_file_generated_check

- block: # Create and Run application services
  - name: Run webstack
    docker_service:
      project_src: "{{ docker_compose_webstack_directory_path }}"
      state: present
      restarted: true
    when: docker_compose_file_generated_check
    register: output
  - debug: var=output


  tags:
    - docker-webstack-up
