---

- block: # Doing pre-check
  - name: Pre-check state
    include: pre_check.yml


- block: # Loop to generate Docker-compose files
  - name: Generate Docker-compose file
    include: generate.yml
    # with_dict: "{{ hostvars[inventory_hostname]['docker_webstack_container_' + webstack_container_name[0]] | default(docker_webstack_container_default) }}"
    # loop_control:
    #   loop_var: docker_webstack_container


- block: # Loop to prepare container environment before run containers
  - name: Prepare container environment before run containers
    include: pre_run.yml
    with_dict: "{{ hostvars[inventory_hostname]['docker_webstack_container_' + webstack_container_name[0]] | default(docker_webstack_container_default) }}"
    loop_control:
      loop_var: docker_webstack_container


- block: # Run all containers (docker-compose up)
  - name: Run container
    include: run.yml
