---

- block: # Run Docker containers
  - name: Run stack containers
    docker_service:
      project_src: "{{ docker_compose_webstack_directory_path }}"
      state: present
      scale:
        web: "{{ docker_webstack_container_web_scale }}"
    register: webstack_container_create_result
  - debug: msg=webstack_container_create_result

- block: # Stop and Destroy Docker containers
  - name: Destroy stack containers
    docker_service:
      project_src: "{{ docker_compose_webstack_directory_path }}"
      state: absent
      scale:
        web: "{{ docker_webstack_container_web_scale }}"
    register: webstack_container_destroy_result
    when: webstack_container_create_result and docker_webstack_container_destroy


  tags:
    - docker-webstack-run
