version: '2'
services:
  haproxy:
    image: dockercloud/haproxy:1.5
    container_name: haproxy
    hostname: haproxy
    restart: always
    ports:
      - 9080:80
    # links:
    #   - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    dns:
      - 8.8.8.8
      - 4.4.4.4

  # web:
  #   image:
