version: '2'
services:
  web:
    image: dockercloud/hello-world
    restart: always

  lb:
    image: dockercloud/haproxy:1.5
    container_name: lb
    hostname: lb
    restart: always
    ports:
      - 9080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - web

