version: '2'
services:
  web:
    image: nttcth/docker-webpy
    restart: always
    links:
      - db

  db:
    image: mariadb:5.5
    container_name: db
    restart: always
    environment:
      - MYSQL_DATABASE='webpy'
      - MYSQL_USER='webpy'
      - MYSQL_ROOT_PASSWORD='123123'
    volumes:
      - /docker/spam/data:/var/lib/mysql

  lb:
    image: dockercloud/haproxy:1.5
    container_name: lb
    restart: always
    ports:
      - 10080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - web

